env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:jest/all
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
parser: babel-eslint
