folders:
  source: src
  output: build
sass:
  source: /sass/
  output: /css/
  main: style.scss
js:
  main: index.js
  source: /js/
  sw: sw.js
endpoint: http://localhost:3000
lighthouse:
  report: lighthouse-report
  opts:
    output: html
    chromeFlags:
      - --headless
    logLevel: info
    view: true
  config:
    extends: lighthouse:default
    settings:
      onlyAudits:
        - 'first-meaningful-paint'
        - 'speed-index'
        - 'first-cpu-idle'
        - 'interactive'
